version: "3.9"

services:
  app:
    build: .
    command: php artisan serve --host 0.0.0.0 --port 8001
    volumes:
      - .:/app
    ports:
      - 8001:8001
      - 389:389
    working_dir: /app

  db-oracle:
    image: oracle/database:21.3.0-ee
    restart: unless-stopped
    volumes:
      - db-data:/usr
    ports:
      - 1521:1521
      - 5500:5500

volumes:
  db-data:

